#!/usr/bin/env ruby

require_relative '../lib/awskeyring_command'

trap('SIGINT') do
  warn "\nExecution aborted.\n"
  exit 1
end

begin
  AwskeyringCommand.start
rescue Keychain::UserCancelledError => e
  warn e.to_s
  exit 1
end
