#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/awskeyring_command'

trap('SIGINT') do
  warn "\nExecution aborted.\n"
  exit 1
end

begin
  AwskeyringCommand.start
rescue Keychain::UserCancelledError => e
  warn e
  exit 1
end
