# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true
      - name: Run filemode
        run: bundle exec rake filemode
      - name: Run Rubocop
        run: bundle exec rake rubocop
      - name: Run Rspec
        run: bundle exec rake spec
      - name: Run Ronn Doc
        run: bundle exec rake ronn
      - name: Run Yard Doc
        run: bundle exec rake yard
      - name: Run build Package
        run: bundle exec rake build
      - uses: actions/upload-artifact@v4
        with:
          name: awskeyring_gem
          path: pkg/awskeyring*.gem
          if-no-files-found: error
